"""Project compact loop ledger entries into a human-readable work log."""

from __future__ import annotations

from pathlib import Path

from trading_assistant.schemas.loop_run_ledger import LoopRunLedgerEntry
from trading_assistant.skills.loop_run_ledger import LoopRunLedgerStore


class WorkLogProjector:
    def __init__(self, ledger_path: Path, work_log_path: Path) -> None:
        self.ledger_path = ledger_path
        self.work_log_path = work_log_path

    def project(self, *, limit: int = 50) -> list[LoopRunLedgerEntry]:
        entries = LoopRunLedgerStore(self.ledger_path).read()
        latest = sorted(
            entries,
            key=lambda entry: (
                entry.completed_at
                or (entry.scheduled_for.isoformat() if entry.scheduled_for else "")
                or entry.generated_at.isoformat()
            ),
            reverse=True,
        )[:limit]
        self.work_log_path.parent.mkdir(parents=True, exist_ok=True)
        body = [
            "# Loop Work Log",
            "",
            "Generated from `memory/findings/loop_run_ledger.jsonl`. Do not edit this file as authority.",
            "",
        ]
        if latest:
            body.append("\n\n".join(entry.work_log_line() for entry in latest))
            body.append("")
        else:
            body.extend([
                "No projected loop entries yet.",
                "",
            ])
        self.work_log_path.write_text("\n".join(body), encoding="utf-8")
        return latest
